[package]
name = "tokenizations"
version = "0.1.3"
license = "MIT"
description = "Tokenizations alignments library"
homepage = "https://github.com/tamuhey/tokenizations"
repository = "https://github.com/tamuhey/tokenizations"
keywords = ["nlp", "text", "algorithm"]
authors = ["Yohei Tamura <tamuhey@gmail.com>"]
readme = "README.md"
documentation = "https://docs.rs/tokenizations/0.1.0/tokenizations/"

[dependencies]
unicode-normalization = "0.1.8"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
