[build-system]
requires = [ "maturin",]
build-backend = "maturin"

[versionup]
tag = true
commit = true
files = [ "src/lib.rs", "Cargo.toml",]
tag_prefix = "python/"

[tool.poetry]
name = "pytokenizations"
version = "0.4.7"
description = ""
authors = [ "Yohei Tamura <tamuhey@gmail.com>",]

[tool.poetry.dependencies]
python = ">=3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
hypothesis = "^4.57.1"
twine = "^1.15.0"
maturin = "^0.7.7"
